services:
  python: # サービスの名前を定義
    image: python:dockerfile-3.13-base # 立ち上げるイメージのrepository名:tag名を指定
    build:  # Dockerfileを相対パスで指定
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: python3.13-20250420  # コンテナ名を指定
    working_dir: /workspace # コンテナの作業ディレクトリを明示
    volumes:  # volumeのマウント
      - ..:/workspace # ホストのカレントディレクトリをコンテナの/workspaceにバインドマウント
    tty: true # コンテナを起動し続ける