services:
  python: # サービスの名前を定義
    image: python:dockerfile-2.0 # イメージのrepository名:tag名を指定
    build:  # Dockerfileを相対パスで指定
      context: .
      dockerfile: Dockerfile
    container_name: python1.0  # コンテナ名を指定
    working_dir: /workspace # コンテナの作業ディレクトリを明示
    volumes:  # volumeのマウント
      - work:/workspace
    tty: true # コンテナを起動し続ける

# ボリュームの定義
volumes:
  work:
